### ISSUE TITLE
Compile working map files

### ISSUE THREAD

**Issue by NervosaX** [fyodorvi/jspm-watch#2]
I'm usually very reliant on using breakpoints and debugger statements, and jspm has been very powerful in the fact that both its outputted variables and its mapped code correctly reflect my source code. 

Through jspm-watch I am instead writing code in es6 and debugging in es5, which makes debugging harder.

Setting sourceMaps to true seem to correctly generate map files, but are not showing when debugging code.

**Comment by fyodorvi** [comment]
@NervosaX 
Thanks for highlighting that.

I revised test project, and, first of all, I was routing `http://localhost:3000/app/app.js` to `./dist/app.js` which led to incorrect Chrome Dev Tools behaviour with source maps.
Now I'm just outputting build to `./dist/app/app.js`, which solves correct source maps pick up. 
But the problem is that souceMap file doesn't contain sources and since you are serving `.dist/` folder (if we are talking about test-project) browser doesn't have access to them (their paths are `../../client/**/*` relative to output folder, that's how SystemJS maps it).

So the simplest solution here will be routing sources with your server:

``` javascript
    browserSync.init({
        ...
        server: {
           ...
            routes: {
                '/client': './client'
                ...
            }
        }
    });
```

Other solution will be adding a folder to Chrome Workspace and mapping it. Which will even allow you to make changes to code files from Dev Tools. That's how your Settings > Workspace may look like:

![http://i.imgur.com/GpYubvR.png](http://i.imgur.com/GpYubvR.png)

I've updated test-project with simplest solution, please pull and tell if it works you now. Thanks.

**Comment by NervosaX** [comment]
Looks good. :) You're really on the ball here.  Thanks for your work on this, jspm bundling has been a sore point for a long time. This seems to cover 0.16.x quite neatly.
